var parentPllAlgs = [];
var parentOllAlgs = [];
var parentPllAlgsSol = [];
var parentOllAlgsSol = [];
var pllAlgs = [];
var ollAlgs = [];
var pllAlgsSol = [];
var ollAlgsSol = [];

parentPllAlgsSol[0] = "A(a) perm: R'FR'B2RF'R'B2R2";
parentPllAlgsSol[1] = "A(b) perm: R2B2RFR'B2RF'R";
parentPllAlgsSol[2] = "U(a) perm: R2URUR'U'R'U'R'UR'";
parentPllAlgsSol[3] = "U(b) perm: RU'RURURU'R'U'R2";
parentPllAlgsSol[4] = "T perm: (RUR'U')(R'FR2U'R'U')(RUR'U')";
parentPllAlgsSol[5] = "Y perm: F(RU'R'U')(RUR'F')(RUR'U')(R'FRF')";
parentPllAlgsSol[6] = "J(a) perm: R'UL'U2RU'R'U2RL";
parentPllAlgsSol[7] = "J(b) perm: (RUR'F')(RUR'U')(R'FR2U'R')";
parentPllAlgsSol[8] = "R(a) perm: (RU2R'U2')RB'R'U'RURBR2U";
parentPllAlgsSol[9] = "R(b) perm: (R'U2RU2')R'F(RUR'U')R'F'R2'U'";
parentPllAlgsSol[10] = "E perm: x'(RU'R'D)(RUR'D')(RUR'D)(RU'R'D')x";
parentPllAlgsSol[11] = "F perm: R'U'F'(RUR'U')(R'FR2U'R'U')(RUR'U)R";
parentPllAlgsSol[12] = "N(a) perm: (RUR'U)(RUR'F'RUR'U'R'FR2U'R')U2(RU'R')";
parentPllAlgsSol[13] = "N(b) perm: (R'URU')R'F'U'FRU(R'FR'F')(RU'R)";
parentPllAlgsSol[14] = "H perm: (M2UM2)U2(M2UM2)";
parentPllAlgsSol[15] = "Z perm: (M2'U')(M2'U')(M'U2')(M2'U2')(M'U2')";
parentPllAlgsSol[16] = "V perm: R'UR'd'(R'F'R2U'R'U)(R'FRF)";
parentPllAlgsSol[17] = "G(a) perm: (R2'u)(R'UR'U')(Ru')R2y'(R'UR)";
parentPllAlgsSol[18] = "G(b) perm: F'U'F(R2u)(R'URU')R(u'R2)";
parentPllAlgsSol[19] = "G(c) perm: (R2F2RU2RU2')R'F(RUR'U')R'FR2";
parentPllAlgsSol[20] = "G(d) perm: (RUR'U'D)(R2U'RU')(R'UR'U)R2u'";

parentPllAlgs[0] = "F2U'L2UR2U'L2UR2F2";//A(a) perm
parentPllAlgs[1] = "U2R2B2U'F2UB2U'F2UR2";//A(b) perm
parentPllAlgs[2] = "D'B2F2DB2R2B2U'L'R'U2L'R'";//U(a) perm
parentPllAlgs[3] = "RLU2RLUB2R2B2D'F2B2D"//U(b) perm
parentPllAlgs[4] = "F2U'F2DR2B2UB2D'R2";//T perm
parentPllAlgs[5] = "L2D'B2D'R2B2DL2U2LDL'F2RU'R'";//Y perm
parentPllAlgs[6] = "F2U'F2DF2D'L2UL2F2";//J(a) perm
parentPllAlgs[7] = "B2L2UL2D'B2DB2U'B2";//J(b) perm
parentPllAlgs[8] = "L2D'R2F2U'R2UL2U'B2LR'F2L'R";//R(a) perm
parentPllAlgs[9] = "F2DB2L2UB2U'F2UR2BF'L2B'F";//R(b) perm
parentPllAlgs[10] = "";//E perm
parentPllAlgs[11] = "";//F perm
parentPllAlgs[12] = "";//N(a) perm
parentPllAlgs[13] = "";//N(b) perm
parentPllAlgs[14] = "";//H perm
parentPllAlgs[15] = "";//Z perm
parentPllAlgs[16] = "";//V perm
parentPllAlgs[17] = "";//G(a) perm
parentPllAlgs[18] = "";//G(b) perm
parentPllAlgs[19] = "";//G(c) perm
parentPllAlgs[20] = "";//G(d) perm

parentOllAlgsSol[0] = "Sune: (RUR'U)(RU2'R')";
parentOllAlgsSol[1] = "Anti-Sune: (R'U'RU')(R'U2R)";
parentOllAlgsSol[2] = "Cross: F(RUR'U')(RUR'U')(RUR'U')F'";
parentOllAlgsSol[3] = "Pi: (RU2)(R2U'R2'U')(R2U2R)";
parentOllAlgsSol[4] = "Headlights: (R2D)(R'U2)(RD')(R'U2R')";
parentOllAlgsSol[5] = "Chameleon: (rUR'U')(r'FRF')";
parentOllAlgsSol[6] = "Bowtie: F'(rUR'U')(r'FR)";
parentOllAlgsSol[7] = "Breackneck: F(RUR'U')(RUR'U')F'";
parentOllAlgsSol[8] = "Anti-Breakneck: F'(L'U'LU)(L'U'LU)F";
parentOllAlgsSol[9] = "Frying Pan: F(RUR'U')F'(RUR'U')(R'FRF')";
parentOllAlgsSol[10] = "Anti-Frying Pan: f(RUR'U')(RUR'U')S'(RUR'U')F'";
parentOllAlgsSol[11] = "Right back squeezy: rU'(r2Ur2'Ur2U')r"
parentOllAlgsSol[12] = "Right front squeezy (r'U)(r2U'r2'U')(r2Ur)";
parentOllAlgsSol[13] = "Couch: S(RUR'U')f'U'F";
parentOllAlgsSol[14] = "Anti-Couch: S(RUR'U')(R'FRf')";
parentOllAlgsSol[15] = "P: f(RUR'U')f'";
parentOllAlgsSol[16] = "Anti-P: f'(L'U'LU)f";
parentOllAlgsSol[17] = "Lightning: (rUR'U)RU2'r'";
parentOllAlgsSol[18] = "Reverse Lightning: (r'U'RU')R'U2r";
parentOllAlgsSol[19] = "Upstairs: F(RUR'U')F'UF(RUR'U')F'";
parentOllAlgsSol[20] = "Downstairs: F'(L'U'LU)FUF(RUR'U')F'";
parentOllAlgsSol[21] = "Moustache: (RUR'U)(RU'R'U)(R'FRF')";
parentOllAlgsSol[22] = "Anti-Moustache (L'U'LU')(L'ULU)(LF'L'F)";
parentOllAlgsSol[23] = "Lefty Square: (r'U2)(RUR'U)r";
parentOllAlgsSol[24] = "Righty Square: (rU2)(R'U'RU')r'";
parentOllAlgsSol[25] = "Kite: (RUR'U')(R'FR2UR'U')F'";
parentOllAlgsSol[26] = "Anti-Kite: (RUR'U)(R'FRF')(RU2'R')";
parentOllAlgsSol[27] = "Fish Salad: f(RUR'U')f'(RUR'U)(RU2'R')";
parentOllAlgsSol[28] = "Untying Shoelaces: F(RU'R'U')(RUR'F')";
parentOllAlgsSol[29] = "Spotted Chameleon: MU(RUR'U')(R'FRF')M'";
parentOllAlgsSol[30] = "Anti-Spotted Chameleon: (R2UR'B'R)U'(R2URBR')";
parentOllAlgsSol[31] = "Dalmation: (RUR'U)(RU2'R')F(RUR'U')F'";
parentOllAlgsSol[32] = "Anti-Dalmation: MUF(RUR'U')F'M'";
parentOllAlgsSol[33] = "Arrow: (rUR'U')r'R(URU'R')";
parentOllAlgsSol[34] = "T: F(RUR'U')F'";
parentOllAlgsSol[35] = "Tying Shoelaces: (RUR'U')(R'FRF')";
parentOllAlgsSol[36] = "Highway: (RU2)(R2U'RU')(R'U2)(FR'F')";
parentOllAlgsSol[37] = "Streetlights: F(RUR'U')RF'(rUR'U')r'";
parentOllAlgsSol[38] = "Bottle Cap: f(RUR'U')(RUR'U')f'";
parentOllAlgsSol[39] = "Rice Cooker: (RUR'U)(RU2R')UF(URU'R')F'";
parentOllAlgsSol[40] = "City: F(RUR'U')R'F'r(URU'r')";
parentOllAlgsSol[41] = "Seein' Headlights: R'U'(R'FRF')UR";
parentOllAlgsSol[42] = "Fung: F(RUR'U')(RUR'U')(RU'R'U')(RUR'F')";
parentOllAlgsSol[43] = "Anti-Fung: R'F(RUR'U')F'UR";
parentOllAlgsSol[44] = "Gun: f(RUR2U')(R'URU')f'";
parentOllAlgsSol[45] = "Anti-Gun: R'F(RUR'F')Ry'(RU'R')";
parentOllAlgsSol[46] = "Squeegee: l'U'l(L'U'LU)l'Ul";
parentOllAlgsSol[47] = "Anti-Squeegee: rUr'(RUR'U)rU'r'";
parentOllAlgsSol[48] = "H: (RUR'U')M'(URU'r')";
parentOllAlgsSol[49] = "Blank: (RU2R')(R'FRF')U2(R'FRF')";
parentOllAlgsSol[50] = "Zamboni: F(RUR'U')S(RUR'U')f'";
parentOllAlgsSol[51] = "Mouse: f(RUR'U')f'UF(RUR'U')F'";
parentOllAlgsSol[52] = "Anti-Mouse: f(RUR'U')f'U'F(RUR'U')F'";
parentOllAlgsSol[53] = "Diagonal: (RUR'U)(R'FRF')U2(R'FRF')";
parentOllAlgsSol[54] = "Crown: (R'FRF')U2(R'FRF')(UF'UF)";
parentOllAlgsSol[55] = "Bunny: MU(RUR'U')M'(R'FRF')";
parentOllAlgsSol[56] = "X: (rUR'U')M2(URU'R')U'M'";

parentOllAlgs[0] = "FU2F'U'FU'F'";//Sune
parentOllAlgs[1] = "F'U2FUF'UF";//Anti-Sune
parentOllAlgs[2] = "U2L2U2F2L2U2F2L2D'UL'DUF2LRUL'R'";//Cross
parentOllAlgs[3] = "B'U2B2UB2UB2U2B'";//Pi
parentOllAlgs[4] = "FU2FDF'U2FD'F2";//Headlights
parentOllAlgs[5] = "B2L2D'F2DL2B2U'R2ULU'R2UL'U'R2";//Chameleon
parentOllAlgs[6] = "DUB2R2UL2D'F2R'DL2D'R'";//Bowtie
parentOllAlgs[7] = "BULU'L'ULU'L'B'";//Breackneck
parentOllAlgs[8] = "R'U'F'UFU'F'UFR";//Anti-Breakneck
parentOllAlgs[9] = "R2UR'BRU'R'B'UBU'B'R'";//Frying Pan
parentOllAlgs[10] = "";//Anti-Frying Pan
parentOllAlgs[11] = "";//Right back squeezy
parentOllAlgs[12] = "";//Right front squeezy
parentOllAlgs[13] = "";//Couch
parentOllAlgs[14] = "";//Anti-Couch
parentOllAlgs[15] = "RBUB'U'R'";//P
parentOllAlgs[16] = "F'L'U'LUF";//Anti-P
parentOllAlgs[17] = "";//Lightning
parentOllAlgs[18] = "";//Reverse Lightning
parentOllAlgs[19] = "";//Upstairs
parentOllAlgs[20] = "";//Downstairs
